<link href="../../../public/css/app.css" rel="stylesheet" type="text/css">
<style type="text/css">
.texto-terminos-politicas {
    color: #000000;
}
</style>

@extends('layouts.buyer')


@section('content')





<!--The following script tag downloads a font from the Adobe Edge Web Fonts server for use within the web page. We recommend that you do not modify it.--><script>var __adobewebfontsappname__=	"dreamweaver"</script><script src="http://use.edgefonts.net/actor:n4:default;acme:n4:default.js" type="text/javascript"></script>
<div class="main">
  <div class="texto-terminos-politicas">
    <main class="contenido">
      <p>Última actualización: 11 de noviembre de 2020</p>
      <p>Al crear una cuenta de Cerca De Mi (según se define en la cláusula 1) o al utilizar cualquier Servicio de Cerca De Mi (según se define a continuación), usted acepta regirse por los siguientes términos y condiciones (los &quot;Términos y Condiciones&quot;).<br>
        Tal como se utiliza en estos Términos y Condiciones, &quot;nosotros&quot; y &quot;Cerca De Mi&quot; significa la Parte Contratante de Cerca De Mi correspondiente (según se define en la Cláusula 4 a continuación).<br>
        Los servicios que ofrece Cerca De Mi en virtud de los Términos y Condiciones incluyen varios productos y servicios para ayudarle a vender bienes y servicios a los compradores, bien sea online (&quot;Servicios online&quot;), en persona (&quot;Servicios POS&quot;) o ambos. Cualquiera de dichos servicios que ofrece Cerca De Mi se refiere en los presentes Términos y Condiciones como los &quot;Servicios&quot;. Las nuevas funciones o herramientas que se agreguen a los Servicios actuales también estarán sujetas a los Términos y Condiciones. Puede revisar la versión más reciente de los Términos y Condiciones en cualquier momento en&nbsp;<a href="/terminos-y-condiciones-negocios">Terminos y Condiciones</a>. Cerca De Mi se reserva el derecho de actualizar y modificar los Términos y Condiciones mediante la publicación de actualizaciones y cambios en el sitio web de Cerca De Mi. Se recomienda que consulte los Términos y Condiciones periódicamente para que se mantenga informado sobre cualquier actualización o cambio que pueda afectarle. y en caso de que no acepte dichos cambios, debe dejar de usar los Servicios.<br>
      Debe leer, estar de acuerdo y aceptar todos los términos y condiciones contenidos o expresamente mencionados en los presentes Términos y Condiciones, incluyendo la <a href="/politica-de-privacidad/">Política de Privacidad</a><a href="/politica-de-privacidad"></a><a href="https://www.cercademi.me/politica-de-privacidad"></a>, de Cerca De Mi antes de poder crear una Cuenta de Cerca De Mi o usar cualquier Servicio de Cerca De Mi. </p>
      <p><br>
        <strong>Los resúmenes en lenguaje cotidiano se ofrecen solo por conveniencia y aparecen en negrita debajo de cada sección, pero estos resúmenes no son vinculantes legalmente. Por favor, lea los Términos y Condiciones, incluyendo cualquier documento al que se haga referencia en estos Términos y Condiciones, para tener una visión completa de sus requisitos legales. Al usar Cerca De Mi o cualquier servicio Cerca De Mi, usted acepta estos términos. Le rogamos revise las actualizaciones ocasionalmente.</strong></p>
      <p>1. Términos de la Cuenta</p>
      <ol start="1" type="1">
        <li>Para acceder y utilizar los      Servicios, debe registrarse para obtener una cuenta de Cerca De Mi      (&quot;Cuenta&quot;) proporcionando su nombre legal completo, dirección      actual, número de teléfono, una dirección de correo electrónico válida, y      cualquier otra información que se indique según sea necesario. Cerca De Mi      puede rechazar su solicitud de Cuenta o cancelar una Cuenta existente por      cualquier motivo, a nuestra entera discreción. </li>
        <li>Usted debe ser mayor de: (i)      18 años o (ii) al menos tener la mayoría de edad en la jurisdicción donde      reside y desde donde utiliza los Servicios para abrir una Cuenta. </li>
        <li>Usted confirma que recibe cualquier      Servicio provisto por Cerca De Mi con el propósito de llevar a cabo una      actividad comercial y no por un propósito personal, familiar o amical </li>
        <li>Usted acepta que Cerca De Mi      utilizará como método principal de comunicación entre ambos la dirección      de correo electrónico que suministró durante el registro para obtener una      Cuenta, o que ha actualizado ocasionalmente. Usted es responsable de      mantener su contraseña segura. Cerca De Mi no puede ni se hará responsable      por ninguna pérdida o daño que surja como resultado de su incapacidad para      mantener la seguridad de su Cuenta y contraseña. </li>
        <li>Usted es responsable de toda actividad y      contenido, como fotos, imágenes, videos, gráficos, contenido escrito,      archivos de audio, código, información o datos cargados, recopilados,      generados, almacenados, mostrados, distribuidos, transmitidos o exhibidos      en o en conexión con su Cuenta (&quot;Materiales&quot;). </li>
        <li>Un incumplimiento o violación de cualquier      término en los Términos y Condiciones, incluida la AUP, según se determine      a la sola discreción de Cerca De Mi, puede resultar en la rescisión      inmediata de sus Servicios. </li>
      </ol>
      <h3>LO QUE SIGNIFICA</h3>
      <p><strong>Usted es responsable de su Cuenta y de los Materiales que suba al Servicio de Cerca De Mi. Recuerde que si viola estos términos podemos cancelar su servicio.</strong><br>
        <strong>Si necesitamos comunicarnos con usted, le enviaremos un correo electrónico.</strong><strong> </strong><br>
        2. Activación de la Cuenta<br>
      <strong>2.1 Propietario de la Tienda o Restaurante </strong></p>
      <ol start="1" type="1">
        <li>Conforme a la Cláusula 2.1(2),      la persona que se registre en el Servicio al abrir una Cuenta será la      parte contratante (en lo sucesivo &quot;Propietario de la Tienda o Restaurante      &quot;) para los fines de nuestros Términos y Condiciones y será la      persona autorizada para usar cualquier Cuenta correspondiente que      proporcionemos al Propietario de la Tienda o Restaurante en relación con      el Servicio. Usted es responsable de garantizar que el nombre del      Propietario de la Tienda o Restaurante (incluyendo la razón social de la      empresa propietaria de la Tienda o Restaurante , si corresponde) esté      visible claramente en el sitio web de la Tienda o Restaurante. </li>
        <li>Si usted se registra en los      Servicios en nombre de su empleador, su empleador será el Propietario de      la Tienda. Si usted se registra en los Servicios en nombre de su      empleador, debe usar la dirección de correo electrónico emitida por su      empleador y declarar y certificar que tiene la autoridad para vincular a      su empleador a nuestros Términos y Condiciones. </li>
        <li>Su Tienda o Restaurante Cerca      De Mi solo puede asociarse a un Propietario de la Tienda. Un Propietario      de Tienda o Restaurante puede tener varias Tiendas o Restaurantes de Cerca      De Mi. &quot;Tienda o Restaurante&quot; significa la Tienda o Restaurante online      o el (los) establecimiento(s) minorista(s) asociados con la Cuenta. </li>
      </ol>
      <p><strong>2.2 Cuentas de Tiendas o Restaurantes administradas por Empleados</strong></p>
      <ol start="1" type="1">
        <li>El Propietario de la Tienda o Restaurante      es responsable por los actos, omisiones o fallas que resulten del uso de      las Cuentas para empleados en el cumplimiento de las obligaciones      establecidas en estos Términos y Condiciones como si fueran actos, omisiones      o fallas del Propietario de la Tienda. </li>
        <li>El Propietario de la Tienda o Restaurante      y los usuarios de las Cuentas para empleados se conocen como un      &quot;Usuario de Cerca De Mi&quot;.</li>
      </ol>
      <h3>LO QUE SIGNIFICA</h3>
      <p><strong>Solo una persona puede ser el &quot;Propietario de la tienda&quot;, en general, la persona que se inscribe en el Servicio de Cerca De Mi. El Propietario de la Tienda o Restaurante es responsable de la Cuenta, está sujeto a los presentes Términos y Condiciones y es responsable de las acciones de las otras personas que accedan a la Cuenta. Si se inscribe en nombre de su empleador, su empleador es el Propietario de la Tienda o Restaurante responsable de su Cuenta.</strong><br>
        <strong>Creamos automáticamente algunas cuentas para que acepte pagos. Usted es responsable de activar y desactivar estas cuentas y de cumplir con sus términos, los cuales con establecidos por distintos terceros.</strong><strong> </strong><br>
        3. Condiciones generales<br>
        Debe leer, estar de acuerdo y aceptar todos los términos y condiciones contenidos en los presentes Términos y Condiciones y la Política de privacidad &nbsp;antes de que pueda convertirse en un Usuario de Cerca De Mi. </p>
      <ol start="1" type="1">
        <li>El servicio al cliente en      relación con los Servicios solo se ofrece a los Usuarios de Cerca De Mi. </li>
        <li>Usted reconoce y acepta que Cerca      De Mi puede enmendar los presentes Términos y Condiciones en cualquier      momento al publicar los correspondientes Términos y Condiciones modificados      y reformulados en el sitio web de Cerca De Mi, disponible en&nbsp;<a href="/termions-y-condiciones-negocios/">https://www.CercaDeMi.me/terminos-y-condiciones-negocios/</a>&nbsp;y que dichas enmiendas a los Términos      y Condiciones entrarán en vigencia a partir de la fecha de publicación. El      uso continuo de los Servicios que haga después de la publicación de los Términos      y Condiciones enmendados en el sitio web de Cerca De Mi constituye su      acuerdo y aceptación de los Términos y Condiciones enmendados. Si no      acepta alguno de los cambios realizados a los Términos y Condiciones, no      continúe usando el Servicio. </li>
        <li>No puede utilizar los      Servicios de Cerca De Mi para ningún propósito ilegal o no autorizado, ni      puede, al hacer uso del Servicio, violar las leyes de su jurisdicción      (incluyendo de manera enunciativa más no limitativa, las leyes de derechos      de autor), las leyes que apliquen a usted en la jurisdicción de su      cliente, o las leyes de Canadá y de la Provincia de Ontario. Usted      cumplirá con todas las leyes, normas y regulaciones aplicables al usar el      Servicio y al cumplir con sus obligaciones según los Términos y Condiciones. </li>
        <li>Usted acepta no reproducir,      duplicar, copiar, vender, revender ni explotar ninguna parte del Servicio,      uso de los Servicios o acceso a los Servicios sin el permiso expreso por      escrito de Cerca De Mi. </li>
        <li>No debe comprar palabras clave      en motores de búsqueda u otras palabras de pago por clic (como Google      AdWords) o nombres de dominio que utilicen Cerca De Mi o las marcas      comerciales de Cerca De Mi y/o sus variaciones o con otra ortografía      similar.8. Las preguntas sobre los Términos y Condiciones se deben enviar al      correo suporte-negocios@cercademi.me.</li>
        <li>Usted entiende que sus      Materiales (excluyendo la información de la tarjeta de crédito) pueden      transferirse sin encriptar e involucrar (a) transmisiones en varias redes;      y (b) cambios para cumplir y adaptarse a los requisitos técnicos de      conexión de redes o dispositivos. La información de la tarjeta de crédito      siempre se cifra durante la transferencia a través de las redes. </li>
        <li>Los Servicios le permiten      enviar ciertas comunicaciones a sus clientes a través del servicio de      mensajes cortos (SMS) (por ejemplo, enviar notificaciones de confirmación      de pedido a través de SMS) (en lo sucesivo los &quot;Servicios de      SMS&quot;). Utilizaremos nuestro proveedor de SMS acordado.</li>
        <li>Usted reconoce y acepta que el      uso de los Servicios, incluyendo la información que transmita a Cerca De      Mi o que Cerca De Mi almacene, se rige según la Política de Privacidad de Cerca      De Mi disponible en&nbsp;<a href="https://www.CercaDeMi.me/politica-de-privacidad">https://www.CercaDeMi.me/politica-de-privacidad</a></li>
        <li>Los Términos y Condiciones pueden      estar disponibles en otros idiomas además del español. En el caso de      cualquier discrepancia o conflicto entre los Términos y Condiciones en español. </li>
        <li> Y la versión de los Términos y Condiciones de Cerca De      Mi disponibles en otros idiomas, la versión más actualizada en español de      dichos Términos y Condiciones disponible en <a href="https://www.cercademi.me/terminos-y-condiciones-negocios">https://www.cercademi.me/terminos-y-condiciones-negocios</a>  prevalecerá. </li>
        <li>Todos los términos y      disposiciones de los presentes Términos y Condiciones tendrán un carácter      vinculante y beneficiarán a las partes firmantes de estos Términos y a sus      respectivos legatarios, sucesores, causahabientes autorizados y      representantes legales. Cerca De Mi podrá ceder estos Términos y      Condiciones sin su preaviso o consentimiento. Usted no tendrá derecho a      ceder o transferir estos Términos y Condiciones, o cualquiera de sus      derechos u obligaciones en virtud de los mismos, a terceras partes sin el      consentimiento previo y por escrito de Cerca De Mi, el cual Cerca De Mi      otorgará o rechazará a su propia discreción. </li>
        <li>Si alguna disposición, o una      parte de la misma, contemplada en estos Términos y Condiciones, por      cualquier motivo, se considerase inválida, ilegal o inejecutable en cualquier      aspecto, dicha nulidad, ilegalidad o inaplicabilidad no afectará a ninguna      otra disposición (ni a la parte no afectada de la disposición) de los Términos      y Condiciones, y los Términos y Condiciones se interpretarán como si dicha      disposición no válida, ilegal o no exigible, o parte de la disposición,      nunca hubiera estado incluida en los Términos y Condiciones. </li>
      </ol>
      <h3>LO QUE SIGNIFICA</h3>
      <p><strong>El servicio de Cerca De Mi nos pertenece. Usted no está autorizado a copiarlo o utilizarlo para ningún propósito ilegal o escueto. </strong><br>
        <strong>Sus Materiales pueden transferirse sin encriptar y pueden alterarse, pero la información de la tarjeta de crédito siempre se encripta.</strong><strong> </strong></p>
      <h2>4. Parte contratante de Cerca De Mi</h2>
      <ul>
        <li>Si la dirección de facturación de su Tienda o Restaurante se encuentra en la región de&nbsp;EMEA&nbsp;u otras jurisdicciones que no figuren en la Cláusula 4(1) o 4(2), incluyendo Europa y Rusia, Oriente Medio, África, América del Sur, el Caribe o México, esta Cláusula 4(3) se aplica a usted: </li>
      </ul>
      <p>a. La &quot;Parte Contratante de Cerca De Mi&quot; significa 9AM Digital, SL., una compañía privada limitada por acciones, incorporada en España con el número de entrada de registro 1-2020-102534 y número de asiento de registro 10/138/468, con sus oficinas registradas ubicadas en el piso puerta D, Calle Miguel Ángel 14, Móstoles, Madrid, España, el número de NIF B01924331 y su sitio web se encuentran en&nbsp;<a href="https://www.shopify.es/">https://www.cercademi.me/</a>.<br>
        b. Usted acepta irrevocable e incondicionalmente someterse a la jurisdicción de los tribunales españoles, que tienen jurisdicción para resolver cualquier disputa que pueda surgir de o en relación con la validez, el efecto, la interpretación o el cumplimiento de los presentes Términos y Condiciones, y de igual manera usted renuncia de manera irrevocable e incondicional a hacer objeción a cualquier reclamo presentado en forma de demanda, acción o procedimiento por Cerca De Mi en cualquier otra jurisdicción. La Convención de las Naciones Unidas sobre los Contratos para la venta internacional de bienes no se aplicará a estos Términos y Condiciones y se excluye expresamente en este documento.</p>
      <h3>LO QUE SIGNIFICA</h3>
      <p><strong>Si surge una disputa, puede iniciar en España.</strong><strong> </strong></p>
      <h2>5. Derechos de Cerca De Mi</h2>
      <ol start="1" type="1">
        <li>Nos reservamos el derecho de modificar o de      discontinuar los Servicios por cualquier motivo, sin previo aviso y en      cualquier momento. No todos los Servicios y funciones están disponibles en      todas las jurisdicciones y no estamos obligados a poner a disposición      Servicios o funciones en ninguna jurisdicción. </li>
        <li>Nos reservamos el derecho de rechazar prestar un      servicio a cualquier persona por cualquier motivo en cualquier momento. </li>
        <li>Podemos, pero no tenemos la obligación de,      eliminar Materiales y suspender o cancelar Cuentas si determinamos, a      nuestro exclusivo criterio, que los bienes o servicios ofrecidos a través      de una Tienda, o los Materiales subidos o publicados en una Tienda,      infringen nuestra&nbsp;<a href="https://www.shopify.es/legal/aup">Acceptable Use Policy (&ldquo;AUP&rdquo;)</a>&nbsp;o estos Términos y      Condiciones.</li>
        <li>El abuso verbal o escrito de cualquier tipo      (incluyendo amenazas de abuso o de retribución) de cualquier cliente de Cerca      De Mi, empleado, miembro o autoridad de Cerca De Mi resultará en el cierre      inmediato de la cuenta. </li>
        <li>Cerca De Mi no realiza una selección previa de      los Materiales y somos libres de rechazar o eliminar cualquier Material      del Servicio, incluyendo su Tienda. </li>
        <li>Nos reservamos el derecho de prestar nuestros      servicios a su competencia y no prometemos la exclusividad de ningún      segmento de mercado en particular. Además, usted reconoce y acepta que los      empleados y contratistas de Cerca De Mi también pueden ser clientes o      comerciantes de Cerca De Mi y que pueden competir con usted, aunque no      pueden usar su Información confidencial (como se define en la Cláusula 6)      para hacerlo. </li>
        <li>En el caso de un reclamo relacionado con la      titularidad de la Cuenta, nos reservamos el derecho de solicitar la      documentación para determinar o confirmar la propiedad de la misma. La      documentación puede incluir, de manera enunciativa más no limitativa, una      copia escaneada de su licencia comercial, de un documento de identidad con      foto emitida por un ente gubernamental, los últimos cuatro dígitos de la      tarjeta de crédito registrada, su estado como empleado de una entidad,      etc. </li>
        <li>Cerca De Mi se reserva el derecho de determinar,      a nuestro exclusivo juicio, la titularidad legítima de la Cuenta y      transferir una Cuenta al Propietario legítimo de la tienda. Si no podemos      determinar razonablemente el Propietario legítimo de la tienda, sin      perjuicio de nuestros otros derechos y recursos, Cerca De Mi se reserva el      derecho de desactivar temporalmente una Cuenta hasta que se haya logrado      una resolución entre las partes en conflicto. </li>
      </ol>
      <h3>LO QUE SIGNIFICA</h3>
      <p>Podemos modificar, cancelar o rechazar el servicio en cualquier momento.<br>
        En el caso de una disputa de propiedad sobre una cuenta de Cerca De Mi, podemos congelar la cuenta o transferirla al propietario legítimo, según lo determinemos. </p>
      <h2>6. Confidencialidad</h2>
      <ul>
        <li>La &quot;Información Confidencial&quot;&nbsp;incluirá, de manera enunciativa mas no limitativa, toda la información relacionada con los negocios de una de las partes y que no sea de conocimiento público, incluida la información comercial específica, procesos técnicos y fórmulas, software, listas de clientes, listas de clientes potenciales, nombres, direcciones y otra información sobre clientes y posibles clientes, diseños de productos, ventas, costos (incluidas las comisiones de procesamiento pertinentes), listas de precios y otra información financiera no publicada, planes de negocio y datos de mercadotecnia, y cualquier otra información confidencial e información sujeta a derechos de propiedad, independientemente de que esté marcada como confidencial o patentada. La Información confidencial de Cerca De Mi incluye toda la información que usted recibe en relación con nosotros o con los Servicios, que no conoce el público en general, incluida la información relacionada con nuestro programa y prácticas de seguridad. </li>
        <li>Cada parte acuerda usar la Información Confidencial de la otra parte únicamente cuando sea necesario para cumplir con sus obligaciones según lo previsto en estos Términos y Condiciones y de conformidad con cualquier otra obligación prevista en estos Términos y Condiciones, incluida la presente Cláusula 6. Cada parte acuerda que tomará todas las medidas razonables, al menos sustancialmente equivalentes a las medidas que toma para proteger su propia información patentada, a fin de evitar la copia, divulgación o uso de dicha Información Confidencial, que no sea (i) por o mediante sus empleados, agentes y subcontratistas que deban tener acceso a dicha Información Confidencial para cumplir con las obligaciones de dicha parte previstas en los presentes, y que están sujetos a obligaciones de confidencialidad para dicha parte que sean al menos tan estrictas como las contenidas en este documento; o (ii) según lo exija cualquier ley, reglamento u orden de cualquier tribunal de jurisdicción apropiada sobre las partes y el asunto contenido en estos Términos y Condiciones, siempre que, si está legalmente permitido, la parte receptora notificará por escrito a la parte divulgadora y usará todos los esfuerzos comercialmente razonables para garantizar que dicha divulgación reciba un tratamiento confidencial. La Información Confidencial no incluirá ninguna información que la parte receptora pueda probar: (A) que ya fuese de conocimiento público, o que ya la parte receptora la conociese o estuviese en posesión de ella, al momento de la divulgación de dicha información; (B) información que sea desarrollada de manera independiente por la parte receptora sin el uso o referencia de la Información Confidencial de la otra parte, y que no incumpla ninguna disposición de estos Términos y Condiciones; o (C) si la parte receptora la obtuvo inmediatamente después de una fuente que no sea la parte divulgadora sin incumplir ninguna disposición de estos Términos y Condiciones. </li>
      </ul>
      <h3>LO QUE SIGNIFICA</h3>
      <p>Tanto usted como Cerca De Mi acuerdan utilizar la Información confidencial de la otra parte únicamente para cumplir con las obligaciones de estos Términos y Condiciones. Se debe proteger y respetar la Información Confidencial. <br>
        7. Limitación de responsabilidad</p>
      <ol start="1" type="1">
        <li>Usted entiende y acepta expresamente      que, en la medida en que lo permitan las leyes aplicables, Cerca De Mi no      será responsable de ningún daño directo, indirecto, incidental, especial,      consecuente o ejemplar, incluidos, entre otros, los daños por pérdida de      beneficios, clientela, uso, datos u otras pérdidas intangibles resultantes      del uso o la imposibilidad de usar el Servicio. </li>
        <li>En la medida en que lo      permitan las leyes aplicables, Cerca De Mi o nuestros proveedores, no      serán responsables en ningún caso por la pérdida de beneficios o cualquier      daño especial, incidental o consecuente que surja de o que esté      relacionado con nuestro sitio, nuestros Servicios o estos Términos y      Condiciones (aunque surjan de la negligencia). Usted acepta indemnizarnos      y mantenernos y (según corresponda) mantener a nuestra casa matriz,      filiales, afiliados, Partners de Cerca De Mi, autoridades, directores,      agentes, empleados y proveedores indemnes de cualquier reclamo o demanda,      incluidos los honorarios razonables de abogados, generados por un tercero      debido al o que surjan del incumplimiento de estos Términos y Condiciones o      de los documentos que incluye por referencia (incluida la AUP), o su      violación de cualquier ley o de los derechos de un tercero. </li>
        <li>Su uso de los Servicios es a      su riesgo y ventura. Los Servicios se proporcionan &quot;tal cual&quot; y      &quot;según disponibilidad&quot; sin ninguna garantía o condición,      expresa, implícita o legal. </li>
        <li>Cerca De Mi no garantiza que      los Servicios serán ininterrumpidos, oportunos, seguros o sin errores. </li>
        <li>Cerca De Mi no garantiza que      los resultados que se pueden obtener del uso de los Servicios sean      precisos o confiables. </li>
        <li>Cerca De Mi no garantiza que la calidad de      cualquier producto, servicio, información u otro material comprado u      obtenido por usted a través de los Servicios satisfará sus expectativas, o      que se corregirá cualquier error en los Servicios. </li>
      </ol>
      <h3>LO QUE SIGNIFICA</h3>
      <p><strong>No nos hacemos responsables si usted infringe la ley, este acuerdo o va en contra de los derechos de un tercero, especialmente si lo demandan.</strong><br>
        <strong>El Servicio se presta &quot;tal cual&quot; por lo que puede tener errores o sufrir interrupciones y no ofrecemos ninguna garantía, además de que nuestra responsabilidad es limitada.</strong><strong> </strong></p>
      <h2>8. Renuncia, divisibilidad y acuerdo completo</h2>
      <p>El hecho de que Cerca De Mi no ejerza o haga valer cualquier derecho o disposición de los Términos y Condiciones no constituirá una renuncia a tal derecho o disposición. Si un tribunal de jurisdicción competente considera que alguna disposición de los Términos y Condiciones, incluidos todos los términos y condiciones y otros documentos que incorpore por referencia, es contraria a la ley, dicha disposición se modificará e interpretará de manera que se cumplan mejor los objetivos de la disposición original en la mayor medida que permita la ley, y la disposición restante de los Términos y Condiciones permanecerá en pleno vigor y efecto.<br>
        Los Términos y Condiciones, incluidos los documentos que estos incorporan por referencia, constituyen el acuerdo completo entre usted y Cerca De Mi y rigen el uso de los Servicios y su Cuenta, reemplazando cualquier acuerdo anterior entre usted y Cerca De Mi (incluyendo, sin limitación, cualquier versión anterior de los Términos y Condiciones).</p>
      <h3>LO QUE SIGNIFICA</h3>
      <p>Si Cerca De Mi decide no hacer cumplir alguna de estas disposiciones en cualquier momento, no significa que renunciemos a ese derecho más adelante.<br>
        Estos Términos y Condiciones conforman el acuerdo que se aplica a usted. Esto significa que ningún acuerdo previo entre usted y Cerca De Mi se aplica si entra en conflicto con los presentes. <br>
        9. Propiedad intelectual y contenido generado por el usuario</p>
      <ol start="1" type="1">
        <li>No reclamamos ningún derecho      de propiedad intelectual sobre los Materiales que usted proporcione al      Servicio de Cerca De Mi. Todos los Materiales que suba le pertenecen.      Puede eliminar su Tienda o Restaurante Cerca De Mi en cualquier momento      eliminando su Cuenta. </li>
        <li>Al subir Materiales, usted      acepta: (a) permitir que otros usuarios de Internet vean los Materiales      que publica públicamente en su Tienda; (b) permitir que Cerca De Mi      almacene, y en el caso de los Materiales que publica públicamente, muestre      y utilice sus Materiales; y (c) que Cerca De Mi puede, en cualquier      momento, revisar y eliminar todos los Materiales enviados a su Servicio,      aunque Cerca De Mi no está obligado a hacerlo. </li>
        <li>Usted conserva la propiedad de      todos los Materiales que suba a la Tienda; sin embargo, al hacer pública      su Tienda, usted acepta permitir que otros vean los Materiales que publica      públicamente en su Tienda. Usted es el único responsable de la conformidad      de los Materiales con las leyes o regulaciones aplicables. </li>
        <li>Cerca De Mi tendrá el derecho y la licencia no      exclusivos para usar los nombres, marcas comerciales, marcas de servicio y      logos asociados a su Tienda o Restaurante para promover el Servicio.</li>
      </ol>
      <h3>LO QUE SIGNIFICA</h3>
      <p><strong>Todo lo que suba es de su propiedad y queda bajo su responsabilidad.</strong><strong> </strong><br>
        10. Pago de Cargos</p>
      <ol start="1" type="1">
        <li>Debe mantener una forma de      pago válida en nuestro archivo para pagar todos los Cargos incurridos y      recurrentes. Cerca De Mi cobrará los Cargos aplicables a cualquier forma      de pago válida que usted autorice (&quot;Forma de pago autorizada&quot;),      y Cerca De Mi continuará cobrando a la forma de pago autorizada los Cargos      aplicables hasta que se cancelen los Servicios, y que se hayan pagado por      completo todos los Cargos pendientes. A menos que se indique lo contrario,      todos los Cargos y otras comisiones se expresan en euros y todos los pagos      se realizarán en la moneda europea. </li>
        <li>Los Cargos por transacción y      los Cargos adicionales se cobrarán de vez en cuando a discreción de Cerca      De Mi. Se le cobrará en cada Fecha de facturación todos los Cargos pendientes      que no se hayan cobrado previamente. Los Cargos aparecerán en una factura,      que se enviará al Propietario de la Tienda o Restaurante a través del      correo electrónico proporcionado. Los usuarios tienen aproximadamente dos      semanas para evocar y resolver cualquier problema relacionado con la      facturación de los Cargos. </li>
        <li>Si no podemos procesar el pago      de los Cargos utilizando una forma de pago autorizada, haremos un segundo      intento de procesar el pago utilizando cualquier forma de pago autorizada      3 días después. Si el segundo intento no tiene éxito, haremos un último      intento 3 días después del segundo intento. Si nuestro último intento      falla, podemos suspender y revocar el acceso a su Cuenta y a los      Servicios. Su Cuenta se reactivará tras el pago de los Cargos pendientes,      más los Cargos aplicables a su próximo ciclo de facturación. Es posible      que no pueda acceder a su Cuenta o a su página principal de la Tienda o Restaurante      durante cualquier período de suspensión. Si los Cargos pendientes      permanecen sin pagar durante 60 días después de la fecha de suspensión, Cerca      De Mi se reserva el derecho de cancelar su Cuenta.</li>
        <li>Todos los Cargos son      exclusivos de las ventas, bienes y servicios gubernamentales, federales,      provinciales, estatales, locales u otros aplicables  u otros impuestos o impuestos      armonizados, cargos o comisiones vigentes actualmente o promulgadas en el      futuro (&ldquo;Impuestos&rdquo;).</li>
        <li>Usted es responsable de todos      los Impuestos aplicables que surjan de o como resultado de la compra de      productos y servicios de Cerca De Mi. En la medida en que Cerca De Mi      cobre estos Impuestos, estos se calculan utilizando las tasas impositivas      que se aplican en función de la dirección de facturación que nos proporcione.      Tales montos son adicionales a los Cargos por dichos productos y servicios      y se facturarán a su forma de pago autorizada. Si está exento del pago de      dichos Impuestos, debe proporcionarnos evidencia de su exención, que en      algunas jurisdicciones incluye un certificado original que cumple con los      requisitos legales aplicables que atestiguan el estado de exención de      impuestos. La exención de impuestos solo se aplicará a partir de la fecha      en que recibamos una evidencia que satisfaga a Cerca De Mi de su exención.      Si Cerca De Mi no le cobra los Impuestos, usted es responsable de      determinar si los Impuestos son pagaderos y, de ser así, remitir usted      mismo los Impuestos a las autoridades fiscales correspondientes en su      jurisdicción.</li>
        <li>Para evitar cualquier duda, todas      las sumas pagaderas por usted a Cerca De Mi bajo estos Términos y      Condiciones se pagarán sin deducciones ni retenciones de ningún tipo.      Aparte de los Impuestos que Cerca De Mi le cobra a usted y que son      remitidos en su nombre a las autoridades fiscales correspondientes,      cualquier otra deducción o retención que exija la ley correrá a su cargo y      se pagará por separado a la autoridad fiscal correspondiente. Cerca De Mi      tendrá derecho a cobrar el monto total de los Cargos estipulados en estos Términos      y Condiciones a su forma de pago autorizado, ignorando cualquier deducción      o retención que pueda ser necesaria.</li>
        <li>Debe mantener actualizada una      ubicación precisa en el menú de administración de su Tienda o Restaurante Cerca      De Mi. Si cambia de jurisdicción, debe actualizar rápidamente su ubicación      en el menú de administración.</li>
        <li>Cerca De Mi no hace reembolsos.</li>
      </ol>
      <h3>LO QUE SIGNIFICA</h3>
      <p><strong>Se requiere un método de pago válido (como una tarjeta de crédito o número de cuenta o cuenta paypal) para todas las tiendas o restaurantes. Se le facturarán sus Cargos por ventas cada 7 días. Cualquier Cargo por transacción o cargos adicionales se cobrarán a través de su método de pago. Si no podemos procesar el pago de los Cargos utilizando su método de pago, lo intentaremos nuevamente en 3 días. Si no podemos procesar el pago de los Cargos en el segundo intento, haremos un tercer y último intento tres días después. Si el pago de los Cargos no se logra procesar después de tres intentos, Cerca De Mi puede congelar su Tienda o Restaurante. Es posible que se le solicite que remita los Impuestos a Cerca De Mi o que los remita usted mismo a su autoridad fiscal local. No se hacen reembolsos.</strong><strong> </strong><br>
        15. Cancelación y Rescisión</p>
      <ol start="1" type="1">
        <li>Puede cancelar su Cuenta y rescindir      los Términos y Condiciones en cualquier momento enviando un correo      electrónico a soporte_negocios@cercademi.me&nbsp;y siguiendo las instrucciones      específicas indicadas en la respuesta de Cerca De Mi. </li>
        <li>Tras la rescisión de los      Servicios por cualquiera de las partes por cualquier motivo: </li>
        <ol start="1" type="1">
          <li>Cerca De Mi dejará de       proporcionarle los Servicios y usted ya no podrá acceder a su Cuenta; </li>
          <li>A menos que se indique lo       contrario en los Términos y Condiciones, no tendrá derecho a ningún       reembolso de ningún Cargo, proporcional o de otro tipo; </li>
          <li>Cualquier saldo pendiente       adeudado a Cerca De Mi por el uso de los Servicios hasta la fecha de entrada       en vigor de dicha rescisión será inmediatamente debido y pagadero en su       totalidad; y </li>
          <li>el sitio web de tu Tienda o Restaurante       se desconectará. </li>
        </ol>
        <li>Si para la fecha de rescisión      del Servicio, queda algún Cargo pendiente adeudado por usted, recibirá una      factura final por correo electrónico. Una vez que la factura se haya      pagado en su totalidad, no se le cobrará nuevamente. </li>
        <li>Nos reservamos el derecho de      modificar o rescindir el Servicio de Cerca De Mi, los Términos y      Condiciones y/o su Cuenta por cualquier motivo, sin previo aviso en      cualquier momento (a menos que la ley estipule lo contrario). La rescisión      de los Términos y Condiciones se realizará sin perjuicio de cualquier otro      derecho u obligación que surja antes de la fecha de rescisión. </li>
        <li>Fraude: sin limitar ningún otro recurso, Cerca De      Mi puede suspender o rescindir su Cuenta si sospechamos que usted (por      condena, resolución, seguro o investigación de depósito en garantía u      otro) ha participado en actividades fraudulentas relacionadas con el uso      de los Servicios. </li>
      </ol>
      <h3>LO QUE SIGNIFICA</h3>
      <p>Para iniciar una rescisión, envíe un correo electrónico&nbsp;a&nbsp;soporte_negocios@cercademi.me. Cerca De Mi responderá con información específica sobre el proceso de rescisión de su cuenta. Si cancela en el transcurso de su ciclo de facturación, tendrá una última factura por correo electrónico.<br>
        Podemos cambiar o rescindir su cuenta en cualquier momento. En caso de fraude suspenderemos o rescindiremos su cuenta. <br>
        16. Modificaciones al Servicio y Precios</p>
      <ol start="1" type="1">
        <li>Los precios para el uso de los      Servicios están sujetos a cambio previo aviso de Cerca De Mi con 30 días      de antelación. Dicho aviso podrá darse en cualquier momento publicando los      cambios en el Sitio Web de Cerca De Mi (cercademi.me) o en el menú de      administración de su Tienda o Restaurante Cerca De Mi a través de un      anuncio. </li>
        <li>Cerca De Mi se reserva el      derecho de modificar o interrumpir los Servicios (o cualquier parte de los      mismos) en cualquier momento y eventualmente, con o sin previo aviso (a      menos que la ley aplicable exija lo contrario). </li>
        <li>Cerca De Mi no será responsable ante usted ni      ante ningún tercero por ninguna modificación, cambio de precio, suspensión      o interrupción del Servicio. </li>
      </ol>
      <h3>LO QUE SIGNIFICA</h3>
      <p><strong>Podemos cambiar o interrumpir el servicio en cualquier momento, sin que nuestra responsabilidad se vea comprometida.</strong><strong> </strong><br>
        17. Servicios externos, Expertos y Mercado de Expertos</p>
      <ol start="1" type="1">
        <li>Cerca De Mi puede      ocasionalmente recomendar, brindarle acceso o habilitar software,      aplicaciones (en lo sucesivo &quot;Aplicaciones&quot;; &quot;Apps&quot; ),      productos, servicios o enlaces a sitios web externos, (denominado en lo      sucesivo colectivamente, &quot;Servicios externos&quot;) para su      consideración o uso, incluso a través de la Tienda o Restaurante de      aplicaciones de Cerca De Mi o el Mercado de Expertos. Dichos Servicios      externos están disponibles solo para su conveniencia, y la compra, acceso      o uso de dichos Servicios externos es únicamente entre usted y el      proveedor de servicios externo correspondiente (en lo sucesivo      &quot;Proveedor externo&quot;). Además de estos Términos y Condiciones,      usted también acepta estar sujeto a los términos adicionales específicos a      servicios que se aplican a los servicios que usted adquiere o que son      proporcionados por proveedores externos.</li>
        <li>No proporcionamos ninguna      garantía de los Servicios externos, ni representamos tales servicios ante      usted. Usted reconoce que Cerca De Mi no controla los Servicios externos y      no será considerado responsable ante usted ni ante cualquier otra persona      de dichos Servicios externos. La disponibilidad de Servicios externos en      los sitios web de Cerca De Mi, incluyendo la Tienda o Restaurante de      aplicaciones Cerca De Mi o el Mercado de Expertos, o la integración o      habilitación de dichos Servicios externos con los Servicios no constituye      o implica un respaldo, autorización, patrocinio o afiliación de Cerca De      Mi. Cerca De Mi no garantiza la disponibilidad de los Servicios externos y      usted reconoce que Cerca De Mi puede deshabilitar el acceso a los      Servicios externos en cualquier momento a su entera discreción y sin      previo aviso. Cerca De Mi no es responsable ni se hace responsable ante      nadie por la interrupción o suspensión del acceso o la desactivación de      cualquier Servicio externo. Cerca De Mi recomienda enfáticamente que      busque asesoramiento especializado antes de utilizar o confiar en los      Servicios externos, para asegurarse de que satisfacen sus necesidades. Las      calculadoras de impuestos, en particular, deben usarse solo como      referencia y no como un sustituto de un asesoramiento fiscal      independiente, para evaluar las tasas de impuestos correctas que debe      cobrar a sus clientes.</li>
        <li>Si instala o habilita un      Servicio externo para usarlo con los Servicios, nos da permiso para dejar      que el Proveedor externo correspondiente acceda a sus datos y otros      Materiales y tome las medidas necesarias para la operación simultánea del      Servicio externo con los Servicios, y cualquier intercambio de datos u      otros Materiales, u otra interacción entre usted y el Proveedor externo es      únicamente entre usted y dicho Proveedor externo. Cerca De Mi no es      responsable de ninguna divulgación, modificación o eliminación de sus      datos u otros Materiales, ni de las pérdidas o daños correspondientes que      pueda sufrir como resultado del acceso de un Servicio externo o un      Proveedor externo a sus datos u otros Materiales.</li>
        <li>Google Maps es un Servicio      externo que se utiliza dentro de los Servicios. Su uso de los Servicios      está sujeto a la aceptación de la [Acceptable Use Policy] de Google Maps y      Earth Enterprise Universal (<a href="https://enterprise.google.com/maps/terms/universal_aup.html">https://enterprise.google.com/maps/terms/universal_aup.html</a>), [Additional Terms of      Service] de Google Maps y Google Earth (<a href="https://maps.google.com/help/terms_maps.html">https://maps.google.com/help/terms_maps.html</a>) y [Privacy Policy] de Google      (<a href="https://www.google.com/intl/ALL/policies/privacy/index.html">https://www.google.com/intl/ALL/policies/privacy/index.html</a>) que puede ser modificado por      Google de eventualmente. </li>
        <li>La relación entre usted y      cualquier Proveedor externo es estrictamente entre usted y dicho Proveedor      externo, y Cerca De Mi no está obligada a intervenir en cualquier disputa      que surja entre usted y un Proveedor externo. </li>
        <li>Bajo ninguna circunstancia Cerca      De Mi será considerado responsable por los daños directos, indirectos,      incidentales, fortuitos, consecuentes, punitivos, extraordinarios,      ejemplares o de cualquier otra índole, que resulten de cualquier Servicio      externo o que estén vinculados con la relación contractual con cualquier      Proveedor externo, incluyendo cualquier Experto. Estas limitaciones se      aplicarán incluso si se ha informado sobre la posibilidad de tales daños a      Cerca De Mi. Las limitaciones mencionadas anteriormente serán aplicadas en      su máxima expresión de acuerdo con la ley vigente. </li>
        <li>Usted acepta indemnizarnos y mantenernos y (según      corresponda) mantener a nuestra casa matriz, filiales, afiliados, Partners      de Cerca De Mi, autoridades, directores, agentes, empleados y proveedores      indemnes por cualquier reclamo o demanda, incluidos los honorarios      razonables de abogados, que surjan del uso de un Servicio externo o de la      relación con un Proveedor externo. </li>
      </ol>
      <h3>LO QUE SIGNIFICA</h3>
      <p><strong>No somos responsables de los servicios externos, así que usted reconoce que los usa bajo su propio riesgo. Si utiliza Servicios externos en la plataforma de Cerca De Mi, quiere decir que nos permite enviar sus datos a esos servicios. Si utiliza los Servicios externos, acepta que no proporcionamos ninguna garantía, así que solicite asesoramiento de antemano.</strong><strong> </strong></p>
      <h2>18. Servicios beta</h2>
      <p>Cerca De Mi puede ocasionalmente, a su entera discreción, invitarlo a que use, a título de prueba, funciones beta o previas al lanzamiento que estén siendo desarrolladas y no estén disponibles aún a todos los Comerciantes (&quot;Servicios beta&quot;). Los Servicios beta pueden estar sujetos a términos y condiciones adicionales que Cerca De Mi le hará llegar antes de que use los Servicios beta. Dichos Servicios beta y todas las conversaciones y materiales relacionados con ellos serán considerados como Información confidencial de Cerca De Mi y estarán sujetos a las disposiciones de confidencialidad de este Acuerdo. Usted acepta, sin limitación de la generalidad de lo anterior, que no hará declaraciones públicas ni que divulgará su participación en los Servicios beta sin el consentimiento previo y por escrito de Cerca De Mi. Cerca De Mi no alega ni garantiza que los Servicios beta funcionen. Cerca De Mi puede interrumpir los Servicios beta en cualquier momento a su entera discreción. Cerca De Mi no será considerado responsable por daños que surjan o estén relacionados con los Servicios beta. Puede que los Servicios beta no funcionen de la misma manera que la versión final. Cerca De Mi puede cambiar o no publicar una versión final o comercial de un Servicio beta a nuestra entera discreción.</p>
      <h2>19. Comentarios y Revisiones</h2>
      <p>Cerca De Mi agradece cualquier idea y/o sugerencia con respecto a mejoras o adiciones a los Servicios. Bajo ninguna circunstancia, la divulgación de cualquier idea, sugerencia o material relacionado o cualquier revisión de los Servicios, de los Servicios externos o de cualquier Proveedor externo (colectivamente, &quot;Comentarios&quot;) a Cerca De Mi estará sujeta a una obligación de confidencialidad o expectativa de compensación. Al enviar los Comentarios a Cerca De Mi (ya sea que se envíen directamente a Cerca De Mi o se publiquen en cualquier foro o página alojados en Cerca De Mi), usted renuncia a todos y cada uno de los derechos en los Comentarios y Cerca De Mi es libre de implementar y usar los Comentarios si lo desea, tal y como usted los propuso o según los modifique Cerca De Mi, sin obtener permiso o licencia de usted o de terceros. Cualquier revisión de un Servicio externo o de un Proveedor externo que envíe a Cerca De Mi debe ser lo más precisa posible de acuerdo a su conocimiento, y no debe ser ilegal, obscena, amenazadora, difamatoria, invadir la privacidad, infringir los derechos de propiedad intelectual o de cualquier manera agraviar a terceros o ser censurable. Cerca De Mi se reserva el derecho (pero no la obligación) de eliminar o de editar un Comentario de los Servicios externos o de los Proveedores externos, pero no inspecciona regularmente los Comentarios publicados.</p>
      <h2>20. Aviso de DMCA (Ley de Derechos de Autor de la Era Digital) y Procedimiento de eliminación</h2>
      <p>Cerca De Mi apoya la protección de la propiedad intelectual y le pide a los comerciantes de Cerca De Mi que hagan lo mismo. Es nuestra política responder a todos los avisos de supuestas infracciones a los derechos de autor. Si alguien cree que uno de nuestros comerciantes está infringiendo sus derechos de propiedad intelectual, puede enviarnos un Aviso de DMCA al email soporte_negocios@cercademi.me. Al recibir un Aviso de DMCA podemos eliminar o desactivar el acceso a los Materiales que se supone infringen el derecho de autor. Una vez que el comerciante reciba un Aviso de procedimiento de eliminación podrá, si objeta la queja, replicar con un aviso de oposición enviando un correo a soporte_negocios@cercademi.me. La persona que origine el reclamo tiene 14 días hábiles después de que recibamos el aviso de oposición para solicitar una orden judicial que impida al comerciante seguir realizando la actividad infractora, de lo contrario restauraremos los materiales. </p>
      <h3>LO QUE SIGNIFICA </h3>
      <p>Cerca De Mi respeta los derechos de propiedad intelectual y usted también debería hacerlo. Si recibimos un Aviso de DMCA podemos desactivar el acceso o eliminar el contenido supuestamente infractor de su sitio web. Si considera que el reclamo no es válido, puede proceder con un contra-aviso.<br>
        Si considera que uno de nuestros comerciantes está infringiendo sus derechos de propiedad intelectual, puede enviar un Aviso de DMCA a Cerca De Mi. Desactivaremos rápidamente el acceso o eliminaremos el contenido y notificaremos al comerciante. Tenga en cuenta que publicamos todos los avisos que recibimos. </p>
      <h2>21. Derechos de terceras partes</h2>
      <p>Salvo para Cerca De Mi y sus afiliados, los Usuarios de Cerca De Mi o cualquier persona que acceda a los Servicios de Cerca De Mi conforme a estos Términos y Condiciones, a menos que se establezca lo contrario en estos Términos y Condiciones, ninguna persona o entidad que no sea parte de estos Términos y Condiciones tendrá derecho de hacer cumplir cualquier término de estos Términos y Condiciones, independientemente de si dicha persona o entidad ha sido identificada por su nombre, como miembro de una clase o como respuesta a una descripción particular. Para evitar cualquier duda, esto no afectará los derechos de cualquier beneficiario o cesionario autorizado de estos Términos.</p>
      <h3>LO QUE SIGNIFICA</h3>
      <p><strong>Solo Cerca De Mi, los Usuarios de Cerca De Mi y las personas que accedan a los Servicios de Cerca De Mi tienen cualquier derecho en virtud de estos Términos y Condiciones.</strong><strong> </strong></p>
      <h2>22. Privacidad y Protección de datos</h2>
      <p>Cerca De Mi se compromete firmemente a proteger la privacidad de su información personal y la información personal de sus clientes. Al utilizar el Servicio, usted reconoce y acepta que la recopilación, el uso y la divulgación de dicha información personal por parte de Cerca De Mi se rigen por nuestra <a href="/politica-de-privacidad">Política de Privacidad</a>.<br>
        Además, si usted: (a) está establecido en el Espacio Económico Europeo (EEE); (b) proporciona bienes o servicios a clientes en el EEE; o (c) que de otra manera está sujeto a los requisitos del Reglamento general de protección de datos de la UE, la recopilación y el uso de información personal por parte de Cerca De Mi de cualquier residente europeo estarán igualmente sujetos a nuestro&nbsp;<a href="/politica-de-privacidad">Política de Privacidad</a>.</p>
      <h3>LO QUE SIGNIFICA</h3>
      <p>El uso y la recopilación de información personal por parte de Cerca De Mi se rigen por nuestra Política de privacidad. Además, si usted o sus clientes se encuentran en Europa, el uso y la recopilación de información personal europea por parte de Cerca De Mi se rigen por nuestro Anexo del Procesamiento de datos.<br>
        9AM Digital, SL.<br>
        Calle Miguel Ángel, 14, Piso 3-D<br>
        Móstoles, Código Postal 28932<br>
        Madrid, España </p>
      <h2>23. Términos y condiciones generales de transporte</h2>
      <p>Cerca De Mi tiene un convenio con DHL PARCEL ESPAÑA para la recogida y entrega de productos, a continuación, detallamos los términos y condiciones a los que están sujetos sus servicios.</p>
      <p>TÉRMINOS Y CONDICIONES GENERALES DE TRANSPORTE DE DHL PARCEL – ESPAÑA – (&ldquo;TÉRMINOS Y CONDICIONES&rdquo;)&nbsp;DHLParcel&nbsp;/&nbsp;Spain&nbsp;/ APS /&nbsp;Spanish&nbsp;V.01-2020&nbsp;&nbsp;<br>
        1. Alcance&nbsp;&nbsp;<br>
        1.1 Los presentes Términos y Condiciones son de aplicación a los siguientes servicios de transporte (los &ldquo;Servicios&rdquo;): DHL PARCEL EUROPLUS DOMÉSTICO: Envíos entre empresas con origen o destino España y Portugal. DHL PARCEL EUROPLUS INTERNACIONAL: Envíos entre empresas con origen o destino España y Europa (excepto Portugal). DHL PARCEL IBERIA: Envíos desde empresas con entrega a particulares, con origen o destino España y Portugal. DHL PARCEL RETURN IBERIA: Envíos de retorno desde particulares a empresas, con origen o destino España y Portugal. DHL PARCEL CONNECT: Envíos desde empresas con entrega a particulares, con origen España y destino internacional (países red&nbsp;Parcel&nbsp;Europe, excepto Portugal). DHL PARCEL RETURN CONNECT: Envíos de&nbsp;retorno desde particulares a empresas con origen fuera de España (países red&nbsp;Parcel&nbsp;Europe, excepto Portugal) y destino España. DHL PARCEL FOR YOU IBERIA (sólo online): Envíos entre particulares con origen en un&nbsp;Servicepoint&nbsp;de DHL y destino España y Portugal. DHL PARCEL FOR YOU INTERNACIONAL (sólo online): Envíos entre particulares con origen en un&nbsp;Servicepoint&nbsp;de DHL y destino internacional (países red&nbsp;Parcel&nbsp;Europe, excepto Portugal).&nbsp;&nbsp;<br>
        1.2 Al contratar los Servicios de DHL, usted como remitente, acepta tanto en su nombre como en nombre del receptor del Envío (&ldquo;destinatario&quot;) y de cualquier otra persona con interés en el Envío, que los presentes Términos y Condiciones se apliquen a los Servicios.&nbsp;&nbsp;<br>
        1.3 El término &quot;Envío&quot; incluye todos los paquetes que viajen bajo la misma carta de porte, pudiendo ser transportados por cualquier medio de transporte que DHL elija en los tramos no terrestres. La &quot;Carta de porte&quot; (incluyendo las versiones electrónicas) deberá incluir un identificador del Envío o documento producido por DHL, o algún sistema automatizado del remitente como una etiqueta, código de barras o nota de entrega. Cada Envío constará de un paquete, a menos que un Servicio permita el envío de varios paquetes bajo una misma Carta de porte. La responsabilidad por cada Envío transportado se limitará a lo establecido en los presentes Términos y Condiciones. Si el remitente requiere una mayor protección, podrá contratar un seguro con un coste adicional.&nbsp;&nbsp;<br>
        1.4 Los Servicios incluyen el transporte de Envíos desde la recepción del mismo por parte de DHL hasta su reparto, incluyendo asimismo los servicios opcionales o servicios auxiliares adicionales seleccionados.&nbsp;&nbsp;<br>
        1.5 No se aplicará ningún otro término ni condición del remitente a los Servicios.&nbsp;<br>
        &nbsp;2. Envíos inaceptables El remitente está de acuerdo en que un Envío se considere inaceptable y, por tanto, quede excluido del transporte (&quot;Envío Prohibido&quot;) si:&nbsp;&nbsp;<br>
        a) Contiene falsificaciones, copias sin licencia de productos, no respeta las restricciones comerciales o embargos aplicables, o está siendo enviado a una parte denegada (por la ONU, la UE, Estados Unidos u otro listado público), o se trata de cualquier otro artículo que no se pueda transportar legalmente;&nbsp;&nbsp;<br>
        b) Requiere un manejo o permisos especiales, incluida la mercancía perecedera que requiere control de temperatura o humedad;&nbsp;&nbsp;<br>
        c) Tiene un embalaje inadecuado o defectuoso;&nbsp;&nbsp;<br>
        d) Contiene animales vivos o plantas, o restos humanos o de animales;&nbsp;<br>
        e) Está clasificado como material peligroso, mercancía peligrosa, prohibida o contiene artículos restringidos por cualquier organización pertinente; por la IATA (Asociación Internacional de Transporte Aéreo) o por la ICAO (Organización de Aviación Civil Internacional) para los Envíos transportados por aire, o por el ADR (Acuerdo Europeo relativo al Transporte Internacional de Mercancías Peligrosas por Carretera) en el caso de Envíos transportados por carretera;&nbsp;&nbsp;<br>
        * f) Su valor bruto (incluido el IVA) es superior a 25.000 euros por Envío (siempre se aplicarán los límites de responsabilidad de DHL);&nbsp;&nbsp;<br>
        ** g) Contiene metales preciosos, joyas y piedras preciosas con un precio de compra de más de 50 euros por pieza y tiene un valor total de más de 500 euros por envío. Objetos de arte, antigüedades, piezas únicas u otros objetos de valor especial y de &quot;alto riesgo&quot;, dinero en efectivo, tarjetas bancarias, instrumentos negociables, sellos, valores, acciones y letras de cambio;&nbsp;&nbsp;<br>
        h) Contiene armas, pseudo armas, munición o artículos de uso militar. DHL no tiene la obligación de verificar si un Envío es inaceptable. Si existe la sospecha razonable de encontrarse ante cualquier&nbsp;Envío Prohibido o por seguridad, aduanas u otros motivos regulados, DHL tendrá derecho a abrir e inspeccionar un Envío. La inspección por parte de DHL no liberará al remitente de sus obligaciones. Si un Envío es considerado inaceptable, DHL podrá (i) rechazar el Envío sin dar los motivos, (ii) devolver el Envío a costa del remitente o mantener el Envío para ser recogido por el remitente, o (iii) aceptar y transportar el Envío sin notificárselo al remitente y, posteriormente, solicitar un cargo adicional por haberse requerido el manejo especial del mismo.&nbsp;&nbsp;<br>
        3. Obligaciones del remitente El remitente tiene las siguientes obligaciones:&nbsp;&nbsp;<br>
        a) Preparar y empaquetar adecuadamente el Envío para garantizar un transporte seguro con el cuidado habitual en su manejo mediante sistemas automatizados;&nbsp;&nbsp;<br>
        b) (i) etiquetar adecuadamente el Envío e (ii) incluir en el Envío la dirección completa del destinatario y del remitente. Cualquier declaración del valor proporcionada para aduanas o para otros fines informativos no se entenderá expresamente como una declaración de interés o valor, en el sentido de las convenciones internacionales de transporte (por ejemplo, CMR, Convenio de Montreal) y disposiciones de los bienes asegurados en virtud de la UPU o de cualquier disposición aplicable comparable que prevea una ampliación de la responsabilidad como consecuencia de dicha declaración;&nbsp;&nbsp;<br>
        c) obtener todas las autorizaciones necesarias en relación con los datos personales facilitados a DHL, incluyendo los datos del destinatario que pudieran ser necesarios para el transporte, despacho de aduanas y entrega, tales como la dirección de correo electrónico y número de teléfono;&nbsp;&nbsp;<br>
        d) cumplir con todos los requisitos de aduanas, importación, exportación, sanciones, embargos y otras leyes y reglamentos, y adjuntar al Envío cualquier documento que sea necesario para cumplir con las leyes y reglamentos aplicables. DHL no tiene ninguna obligación de verificar la exactitud e integridad de los documentos. Si faltara algún documento, el remitente lo enviará inmediatamente, a más tardar dentro de los siguientes cinco (5) días hábiles. A falta de recepción en dicho plazo, DHL podrá tratar el Envío como Envío Prohibido en virtud de la Sección 2. El remitente deberá indemnizar y mantener indemne a DHL por cualquier pérdida o daño que se derive de la falta de cumplimiento por parte del remitente de las leyes o reglamentos aplicables y de sus obligaciones contenidas en las secciones 2 y 3. Dicha indemnización incluye los daños causados a las personas, instalaciones, terceros o a otros Envíos debido a la entrega a DHL de Envíos Prohibidos, así como las sanciones, multas, acciones y reclamaciones interpuestos por las autoridades debido a las infracciones en materia de aduanas o el incumplimiento de las leyes de importación y exportación por parte del remitente.&nbsp;&nbsp;<br>
        4. Servicios y obligaciones de DHL&nbsp;&nbsp;<br>
        4.1 Entrega: Servicios con entrega a empresas: DHL transportará los Envíos a su destino y los entregará en la dirección del destinatario especificada por el remitente, salvo indicación expresa en otro sentido. Los Envíos a direcciones con un área de recepción central serán entregados a esa zona. En ausencia del destinatario o de otra persona en el domicilio, o cuando DHL no pueda razonablemente hacer la entrega, el envío será almacenado en la delegación de DHL de destino. DHL informará al destinatario de tal falta de entrega. Si el peso o volumen del Envío, o las características funcionales del inmueble no permiten a una persona la entrega en la dirección especificada, ésta se efectuará a puerta de calle con los medios de descarga facilitados por el consignatario o en la delegación de DHL de destino. Servicios con entrega a particulares: DHL transportará los Envíos a su destino y los entregará en la dirección especificada por el remitente, que podrá ser un&nbsp;Servicepoint&nbsp;de DHL o la dirección del destinatario. En este último caso, en ausencia del destinatario o de otra persona en el domicilio o cuando DHL no pueda razonablemente hacer la entrega, DHL podrá&nbsp;entregarlos a un vecino del destinatario o mantenerlos guardados para su recogida por el destinatario en un&nbsp;Servicepoint&nbsp;de DHL o en una instalación de almacenamiento similar por un período de 10 días naturales a contar a partir del día siguiente al día del aviso de DHL al cliente. Si el peso o volumen del Envío, o las características funcionales del inmueble no permiten a una persona la&nbsp;entrega en la dirección especificada, ésta se efectuará a puerta de calle.&nbsp;&nbsp;<br>
        *** 4.2 DHL podrá utilizar dispositivos electrónicos para dejar constancia de la entrega de un Envío. Dicha documentación electrónica constituirá una prueba suficiente de la entrega.&nbsp;<br>
        4.3 Si un Envío se considera que es inadmisible de conformidad con la Sección 2, se ha infravalorado a efectos aduaneros, el destinatario no puede ser identificado o localizado, o se niega a la recepción o al pago de los gastos de aduana u otros gastos del Envío, DHL hará esfuerzos razonablemente necesarios para devolver el Envío al remitente a costa del remitente. En su defecto y cuando la ley aplicable lo permita, el envío podrá ser liberado, eliminado o vendido de conformidad con lo dispuesto en la ley y sin incurrir en ningún tipo de responsabilidad respecto al remitente o cualquier otra persona, y se aplicarán las ganancias a los gastos de aduana, gastos de envío y a los costes administrativos relacionados, tras lo cual las ganancias restantes serán devueltas al remitente. Cuando la legislación local lo permita, DHL tendrá derecho a destruir cualquier Envío que cualquier ley impida a DHL devolver al remitente, así como cualquier Envío de mercancías peligrosas o de mercancías perecederas.&nbsp;&nbsp;<br>
        4.4 DHL hará todo el esfuerzo razonable para entregar el Envío de acuerdo con sus tiempos de tránsito regulares y que son estimados.&nbsp;&nbsp;<br>
        4.5 DHL podrá seleccionar la ruta para el transporte y subcontratar la totalidad o parte del Servicio.&nbsp;<br>
        &nbsp;4.6 DHL pondrá a disposición del destinatario opciones de entrega alternativas, como &ldquo;Entrega en&nbsp;Servicepoint&rdquo;, &ldquo;Día de entrega preferido&rdquo; o &ldquo;Entrega en Vecino&rdquo;, quien deberá residir con proximidad inmediata al lugar de entrega original. En caso de que no pueda realizarse alguna de las entregas mencionadas, DHL procederá según descrito en el punto 4.1. DHL no asumirá responsabilidad alguna por cualquier daño o pérdida causados al remitente o destinatario como consecuencia de la elección de alguna de las modalidades de entrega anteriormente citadas&nbsp;y&nbsp;por lo tanto, no imputable a circunstancias bajo el control de DHL.&nbsp;&nbsp;<br>
        4.7 Los Envíos no pueden ser enviados a apartados de correos o códigos postales.&nbsp;&nbsp;<br>
        4.8 Puede encontrar más detalles acerca de los Servicios y opciones de entrega de DHL disponibles para cada producto en cada país, en www.dhl.com, en el servicio de atención al cliente o en un&nbsp;Servicepoint&nbsp;de DHL.&nbsp;&nbsp;<br>
        5. Cargos y derechos A no ser que se acuerde de otra manera:&nbsp;&nbsp;<br>
        5.1 El precio para el transporte y otros Servicios (&ldquo;Cargos&quot;) se abonará de acuerdo con las tarifas de DHL aplicables en ese momento. A menos que se especifique lo contrario, los Cargos excluyen impuestos y cargos de aduana (&ldquo;Derechos&quot;). El remitente deberá pagar los Cargos antes de la realización del Envío y DHL solicitará al destinatario pagar o reembolsar los Derechos.&nbsp;&nbsp;<br>
        5.2 El remitente o el destinatario, cuando DHL actúe en nombre del destinatario, deberá pagar o reembolsar a DHL todos los Cargos y Derechos debidos por Servicios prestados por DHL o en los que haya incurrido DHL en nombre del remitente o del destinatario. Se requerirá el pago de los Derechos antes de la entrega. El pago realizado por el destinatario liberará al remitente de sus responsabilidades de pago.&nbsp;&nbsp;<br>
        5.3 Es responsabilidad del remitente informar adecuadamente al destinatario de los Cargos y Derechos previstos. Si el destinatario se niega a pagar los Cargos y Derechos adeudados, ello se considerará una negativa a aceptar la entrega y el remitente seguirá siendo responsable solidario de dicho pago. En el caso de que ninguna de las partes acceda a pagar dichos Cargos y Derechos, DHL actuará según lo establecido en el apartado 4.3.&nbsp;&nbsp;<br>
        6. Responsabilidad de DHL&nbsp;&nbsp;<br>
        6.1 La responsabilidad de DHL en relación a cualquier Envío está limitada con arreglo a las siguientes disposiciones obligatorias:&nbsp;&nbsp;<br>
        a) Para los Envíos internacionales transportados por carretera, la responsabilidad de DHL será o se considerará que está limitada por la Convención para el Transporte Internacional de Mercancías por Carretera (CMR) a la menor de (i) el valor actual de mercado o el valor declarado, o (ii) 8,33 Derechos Especiales de Giro por kilogramo (lo cual equivale aproximadamente a 10 €/kg). b) Para los envíos nacionales transportados por carretera, la responsabilidad de DHL estará limitada en los términos previstos en la Ley del Contrato de Transporte Terrestre de Mercancías y no podrá exceder de 1/3 IPREM/día/kg (lo cual equivale a 5,98 €/kg); c) Para los Envíos transportados por vía aérea (incluyendo el transporte combinado por carretera o paradas en el camino), la responsabilidad de DHL está limitada por el Convenio de Montreal o el Convenio de Varsovia, según corresponda, o en ausencia de dichos convenios, a la menor de (i) el valor actual de mercado o el valor declarado, o (ii) 19 derechos especiales de giro por kilogramo (lo cual equivale a aproximadamente 23 €/kg). d) Para los Envíos transportados por vía marítima, la responsabilidad estará limitada por lo dispuesto en la legislación de transporte marítimo aplicable.&nbsp;&nbsp;<br>
        6.2 La responsabilidad de DHL se limita estrictamente a la pérdida y/o&nbsp;daño directos&nbsp;al envío y a los límites por kilogramo establecidos en esta Sección 6. Todos los demás tipos de pérdidas o daños quedan excluidos (incluyendo, pero no limitado a la pérdida de beneficios, ingresos, intereses y futuro negocio), ya sea tal pérdida o daño, especial o indirecto, e incluso si el riesgo de tal pérdida o daño fue comunicado a DHL. Excepto que sea de aplicación el Convenio de Montreal, esta limitación no se aplicará a los daños debidos a una conducta dolosa por parte de DHL, o que, de acuerdo con la legislación aplicable, se considere como equivalente a una conducta dolosa.&nbsp;&nbsp;<br>
        6.3 Salvo que se estipule otro plazo en cualquier ley aplicable, DHL deberá ser notificado por escrito en el momento de la entrega en caso de daño aparente causado al Envío y, a más tardar dentro de los 7 días siguientes a la entrega excepto domingos y festivos en caso de daño o pérdida no aparente. Salvo que se estipule otra cosa en cualquier disposición o ley aplicable, las acciones derivadas del contrato de transporte prescriben al año.&nbsp;&nbsp;<br>
        7. Seguro de Envío&nbsp;&nbsp;<br>
        7.1 DHL responderá de las pérdidas y/o daños a los Envíos de conformidad con la limitación de responsabilidad establecida en los presentes Términos y Condiciones.&nbsp;&nbsp;<br>
        7.2 Si el remitente considera insuficiente dicho límite: Para DHL PARCEL EUROPLUS, DHL PARCEL IBERIA y DHL PARCEL CONNECT: puede hacer una declaración de valor y DHL puede proporcionarle un seguro adicional que cubra el valor de los daños o pérdidas causados en un Envío, siempre que el Envío cumpla con los presentes Términos y Condiciones y el remitente dé instrucciones por escrito a DHL en este sentido y pague la prima correspondiente. Para el servicio DHL PARCEL FOR YOU IBERIA: DHL le ofrece la posibilidad de concertar un seguro del envío con una cobertura máxima de 200 euros, mediante el pago de la prima correspondiente. DHL le indemnizará por el importe acreditado&nbsp;en la factura, con el límite señalado, siempre que el Envío cumpla con los presentes Términos y Condiciones.&nbsp;&nbsp;<br>
        7.3 El seguro no cubre pérdidas o daños indirectos, ni la pérdida o daños causados por retrasos. Quedan excluidos de la cobertura del seguro indicada en la Sección 7.2:&nbsp;&nbsp;<br>
        a) La pérdida y daños en los Envíos Prohibidos en virtud de la Sección 2;&nbsp;&nbsp;<br>
        b) La pérdida y daños en los Envíos causados por un embalaje insuficiente o defectuoso;&nbsp;&nbsp;<br>
        c) La pérdida y daños en los Envíos causados por el remitente;&nbsp;&nbsp;<br>
        d) La pérdida y daños en los Envíos reclamados fuera de los plazos establecidos.&nbsp;&nbsp;<br>
        7.4 Puede encontrar más detalles del seguro de transporte aplicable a cualquier Servicio disponible en www.dhlparcel.es.&nbsp;&nbsp;<br>
        8. Despacho de aduanas DHL podrá realizar cualquiera de las siguientes actividades en nombre del remitente con el fin de prestar sus Servicios:&nbsp;&nbsp;<br>
        8.1 Completar todos los documentos, modificar los códigos de productos o Servicios y pagar los derechos e impuestos exigibles por las leyes y reglamentos aplicables.&nbsp;&nbsp;<br>
        8.2 Actuar como agente de aduanas del remitente para cuestiones relativas al control de la exportación y como destinatario, únicamente con el propósito de designar un agente de aduanas para realizar los despachos de aduana y los ingresos.&nbsp;&nbsp;<br>
        8.3 Redirigir el Envío al agente de importación del destinatario u a otra dirección, a petición de cualquier persona que DHL razonablemente crea que está autorizado.&nbsp;&nbsp;<br>
        9. Circunstancias fuera del control de DHL&nbsp;DHL&nbsp;no es responsable por ninguna pérdida o daño causado por circunstancias que estén fuera del control razonable de DHL. Estas circunstancias incluyen, pero no se limitan a (i) daño eléctrico o magnético o supresión de imágenes electrónicas o fotográficas, datos o grabaciones; (ii) cualquier defecto o característica relacionada con la naturaleza del Envío, incluso si éste es conocido por DHL; (iii) cualquier acto u omisión de una persona no empleada o contratada por DHL (por ejemplo, el remitente, el destinatario, un tercero, agentes de aduanas u otro funcionario del gobierno); (iv) cualquier evento de fuerza mayor (por ejemplo, terremotos, ciclones, tormentas, inundaciones, niebla, guerra, accidente de avión, embargo, disturbios, conmoción civil o acción industrial; y (v) cualquier otro motivo previsto en la ley aplicable.&nbsp;&nbsp;<br>
        10. Otros&nbsp;&nbsp;<br>
        10.1 DHL recogerá, almacenará y procesará los datos personales facilitados por el remitente o el destinatario cuando sea necesario para la prestación de los Servicios, de conformidad con las leyes aplicables y la política de Privacidad de Datos de Deutsche Post DHL disponible en www.logistics.dhl/content/dam/dhl/local/es/core/documents/pdf/es-legal-política-de-privacidad-de-datosdpdhl-es.pdf. DHL notificará a los tribunales y autoridades públicas los datos de los clientes que puedan ser legalmente requeridos.&nbsp;&nbsp;<br>
        10.2 La invalidez o inaplicabilidad de cualquier disposición no afectará a ninguna otra disposición de estos Términos y Condiciones. Las partes deberán sustituir la disposición ineficaz por una nueva disposición que sea efectiva y se corresponda, dentro de lo posible, al significado y el propósito de la disposición que ha sido reemplazada, y respete los otros Términos.&nbsp;&nbsp;<br>
        10.3 DHL y el Cliente que no sea consumidor o usuario, según la definición dada por la normativa española, acuerdan someter las disputas en relación con los presentes Términos y Condiciones y/o&nbsp;Servicios prestados a los Juzgados y Tribunales de San Sebastián y se regirán por la ley del país de origen del Envío. El remitente se somete irrevocablemente a dicha jurisdicción, salvo que contradiga la ley aplicable.&nbsp;&nbsp;</p>
      <p>*Para el envío de mercancías peligrosas en cantidades limitadas (LQ) y baterías de litio contacte con atención al cliente de DHL.&nbsp;&nbsp;<br>
        **Limitación no aplicable a Servicios DHL PARCEL EUROPLUS.&nbsp;&nbsp;<br>
        ***Para envíos con destino internacional excepto Portugal y España, la entrega en vecino y/o el plazo de permanencia en&nbsp;Servicepoint&nbsp;puede variar en función del país de destino.&nbsp;</p>
      <p>&nbsp;</p>
    </main>
  </div>
</div>
<p>@endsection</p>
